/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Chapter {
  'id' : string,
  'owner' : Principal,
  'name' : string,
  'subjectId' : string,
}
export interface Lecture {
  'id' : string,
  'status' : string,
  'duration' : bigint,
  'owner' : Principal,
  'telegramLink' : string,
  'name' : string,
  'chapterId' : string,
}
export interface Stats {
  'totalStudyMinutes' : bigint,
  'completedLectures' : bigint,
  'pendingTasks' : bigint,
}
export interface StudySession {
  'id' : string,
  'duration' : bigint,
  'owner' : Principal,
  'date' : string,
}
export interface Subject { 'id' : string, 'owner' : Principal, 'name' : string }
export interface Task {
  'id' : string,
  'title' : string,
  'owner' : Principal,
  'date' : string,
  'completed' : boolean,
  'category' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addStudySession' : ActorMethod<[string, bigint], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createChapter' : ActorMethod<[string, string], string>,
  'createLecture' : ActorMethod<[string, bigint, string, string], string>,
  'createSubject' : ActorMethod<[string], string>,
  'createTask' : ActorMethod<[string, string, string], string>,
  'deleteChapter' : ActorMethod<[string], undefined>,
  'deleteLecture' : ActorMethod<[string], undefined>,
  'deleteSubject' : ActorMethod<[string], undefined>,
  'deleteTask' : ActorMethod<[string], undefined>,
  'getAllSubjects' : ActorMethod<[], Array<Subject>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChapter' : ActorMethod<[string], Chapter>,
  'getChaptersBySubject' : ActorMethod<[string], Array<Chapter>>,
  'getLecture' : ActorMethod<[string], Lecture>,
  'getLecturesByChapter' : ActorMethod<[string], Array<Lecture>>,
  'getStats' : ActorMethod<[string], Stats>,
  'getStreak' : ActorMethod<[Principal], bigint>,
  'getStudySession' : ActorMethod<[string], StudySession>,
  'getStudySessionsByDate' : ActorMethod<[string], Array<StudySession>>,
  'getSubject' : ActorMethod<[string], Subject>,
  'getTask' : ActorMethod<[string], Task>,
  'getTasksByDate' : ActorMethod<[string], Array<Task>>,
  'getTotalMinutesForDate' : ActorMethod<[string], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markLectureDone' : ActorMethod<[string], undefined>,
  'markTaskComplete' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateStreak' : ActorMethod<[], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];