/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Subject = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Chapter = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'subjectId' : IDL.Text,
});
export const Lecture = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'duration' : IDL.Nat,
  'owner' : IDL.Principal,
  'telegramLink' : IDL.Text,
  'name' : IDL.Text,
  'chapterId' : IDL.Text,
});
export const Stats = IDL.Record({
  'totalStudyMinutes' : IDL.Nat,
  'completedLectures' : IDL.Nat,
  'pendingTasks' : IDL.Nat,
});
export const StudySession = IDL.Record({
  'id' : IDL.Text,
  'duration' : IDL.Nat,
  'owner' : IDL.Principal,
  'date' : IDL.Text,
});
export const Task = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'date' : IDL.Text,
  'completed' : IDL.Bool,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addStudySession' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createChapter' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'createLecture' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createSubject' : IDL.Func([IDL.Text], [IDL.Text], []),
  'createTask' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'deleteChapter' : IDL.Func([IDL.Text], [], []),
  'deleteLecture' : IDL.Func([IDL.Text], [], []),
  'deleteSubject' : IDL.Func([IDL.Text], [], []),
  'deleteTask' : IDL.Func([IDL.Text], [], []),
  'getAllSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChapter' : IDL.Func([IDL.Text], [Chapter], ['query']),
  'getChaptersBySubject' : IDL.Func([IDL.Text], [IDL.Vec(Chapter)], ['query']),
  'getLecture' : IDL.Func([IDL.Text], [Lecture], ['query']),
  'getLecturesByChapter' : IDL.Func([IDL.Text], [IDL.Vec(Lecture)], ['query']),
  'getStats' : IDL.Func([IDL.Text], [Stats], ['query']),
  'getStreak' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getStudySession' : IDL.Func([IDL.Text], [StudySession], ['query']),
  'getStudySessionsByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(StudySession)],
      ['query'],
    ),
  'getSubject' : IDL.Func([IDL.Text], [Subject], ['query']),
  'getTask' : IDL.Func([IDL.Text], [Task], ['query']),
  'getTasksByDate' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
  'getTotalMinutesForDate' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markLectureDone' : IDL.Func([IDL.Text], [], []),
  'markTaskComplete' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateStreak' : IDL.Func([], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Subject = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Chapter = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'subjectId' : IDL.Text,
  });
  const Lecture = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'duration' : IDL.Nat,
    'owner' : IDL.Principal,
    'telegramLink' : IDL.Text,
    'name' : IDL.Text,
    'chapterId' : IDL.Text,
  });
  const Stats = IDL.Record({
    'totalStudyMinutes' : IDL.Nat,
    'completedLectures' : IDL.Nat,
    'pendingTasks' : IDL.Nat,
  });
  const StudySession = IDL.Record({
    'id' : IDL.Text,
    'duration' : IDL.Nat,
    'owner' : IDL.Principal,
    'date' : IDL.Text,
  });
  const Task = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'date' : IDL.Text,
    'completed' : IDL.Bool,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addStudySession' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createChapter' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'createLecture' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createSubject' : IDL.Func([IDL.Text], [IDL.Text], []),
    'createTask' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'deleteChapter' : IDL.Func([IDL.Text], [], []),
    'deleteLecture' : IDL.Func([IDL.Text], [], []),
    'deleteSubject' : IDL.Func([IDL.Text], [], []),
    'deleteTask' : IDL.Func([IDL.Text], [], []),
    'getAllSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChapter' : IDL.Func([IDL.Text], [Chapter], ['query']),
    'getChaptersBySubject' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Chapter)],
        ['query'],
      ),
    'getLecture' : IDL.Func([IDL.Text], [Lecture], ['query']),
    'getLecturesByChapter' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Lecture)],
        ['query'],
      ),
    'getStats' : IDL.Func([IDL.Text], [Stats], ['query']),
    'getStreak' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getStudySession' : IDL.Func([IDL.Text], [StudySession], ['query']),
    'getStudySessionsByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StudySession)],
        ['query'],
      ),
    'getSubject' : IDL.Func([IDL.Text], [Subject], ['query']),
    'getTask' : IDL.Func([IDL.Text], [Task], ['query']),
    'getTasksByDate' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
    'getTotalMinutesForDate' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markLectureDone' : IDL.Func([IDL.Text], [], []),
    'markTaskComplete' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateStreak' : IDL.Func([], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };